-- Phase 1: Audit Trail
CREATE TABLE IF NOT EXISTS login_logs (
    id SERIAL PRIMARY KEY,
    admin_id INTEGER REFERENCES admin(id),
    nickname VARCHAR(255),
    login_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45)
);

ALTER TABLE customers ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE asset_roster ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE inactive_cust ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service_tiers ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE warehouse_location ADD COLUMN IF NOT EXISTS inputter VARCHAR(255), ADD COLUMN IF NOT EXISTS inputter_tms TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- Phase 2: Data Normalization (Amount to DECIMAL)
UPDATE transactions SET amount = NULLIF(REGEXP_REPLACE(amount, '[^0-9]', '', 'g'), '') WHERE amount LIKE 'Rp %' OR amount LIKE '%,%' OR amount LIKE '%.%';
ALTER TABLE transactions ALTER COLUMN amount TYPE DECIMAL(15,2) USING amount::DECIMAL;

UPDATE ocr_data SET amount = NULLIF(REGEXP_REPLACE(amount, '[^0-9]', '', 'g'), '') WHERE amount LIKE 'Rp %' OR amount LIKE '%,%' OR amount LIKE '%.%';
ALTER TABLE ocr_data ALTER COLUMN amount TYPE DECIMAL(15,2) USING amount::DECIMAL;

ALTER TABLE expenses ALTER COLUMN amount TYPE DECIMAL(15,2) USING amount::DECIMAL;

-- (Optional tables if they exist, ignoring errors if they don't)
DO  
BEGIN
    BEGIN
        ALTER TABLE invoices ALTER COLUMN amount TYPE DECIMAL(15,2) USING amount::DECIMAL;
    EXCEPTION WHEN OTHERS THEN NULL; END;
END ;

-- Phase 2: Dates to TIMESTAMPTZ
ALTER TABLE customers ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt"::TIMESTAMPTZ;
ALTER TABLE asset_roster ALTER COLUMN tanggal_perubahan TYPE TIMESTAMPTZ USING tanggal_perubahan::TIMESTAMPTZ;
ALTER TABLE stock_asset_roster ALTER COLUMN tanggal_perubahan TYPE TIMESTAMPTZ USING tanggal_perubahan::TIMESTAMPTZ;
ALTER TABLE ocr_data ALTER COLUMN date TYPE TIMESTAMPTZ USING date::TIMESTAMPTZ;
ALTER TABLE expenses ALTER COLUMN date TYPE TIMESTAMPTZ USING date::TIMESTAMPTZ;

-- Ignore errors for tables that might not exist yet
DO  
BEGIN
    BEGIN ALTER TABLE inactive_cust ALTER COLUMN createdat TYPE TIMESTAMPTZ USING createdat::TIMESTAMPTZ; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TABLE inactive_cust ALTER COLUMN inactiveat TYPE TIMESTAMPTZ USING inactiveat::TIMESTAMPTZ; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TABLE invoices ALTER COLUMN due_date TYPE TIMESTAMPTZ USING due_date::TIMESTAMPTZ; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TABLE password_resets ALTER COLUMN expires_at TYPE TIMESTAMPTZ USING expires_at::TIMESTAMPTZ; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TABLE password_resets ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::TIMESTAMPTZ; EXCEPTION WHEN OTHERS THEN NULL; END;
END ;
