                                                                                                                                                                                                          pg_get_viewdef                                                                                                                                                                                                          
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  WITH customerexpectedinvoices AS (                                                                                                                                                                                                                                                                                                                                                                                             +
          SELECT c.id AS customer_id,                                                                                                                                                                                                                                                                                                                                                                                            +
             c.village AS node,                                                                                                                                                                                                                                                                                                                                                                                                  +
             COALESCE(replace(replace(replace(st.price, 'Rp'::text, ''::text), ' '::text, ''::text), '.'::text, ''::text)::numeric, 0::numeric) AS expected_amount,                                                                                                                                                                                                                                                              +
             generate_series((date_trunc('month'::text, (c."createdAt"::timestamp with time zone AT TIME ZONE 'Asia/Jakarta'::text))::date + (EXTRACT(day FROM (c."createdAt"::timestamp with time zone AT TIME ZONE 'Asia/Jakarta'::text)) - 1::numeric)::integer)::timestamp with time zone, CURRENT_DATE::timestamp with time zone, '1 mon'::interval)::date AS virtual_due_date                                              +
            FROM customers c                                                                                                                                                                                                                                                                                                                                                                                                     +
              LEFT JOIN service_tiers st ON TRIM(BOTH FROM c.service) ~~* st.name                                                                                                                                                                                                                                                                                                                                                +
           WHERE c.status = 'Active'::text                                                                                                                                                                                                                                                                                                                                                                                       +
         ), unpaidinvoices AS (                                                                                                                                                                                                                                                                                                                                                                                                  +
          SELECT cei.node,                                                                                                                                                                                                                                                                                                                                                                                                       +
             cei.virtual_due_date,                                                                                                                                                                                                                                                                                                                                                                                               +
             cei.expected_amount                                                                                                                                                                                                                                                                                                                                                                                                 +
            FROM customerexpectedinvoices cei                                                                                                                                                                                                                                                                                                                                                                                    +
           WHERE NOT (EXISTS ( SELECT 1                                                                                                                                                                                                                                                                                                                                                                                          +
                    FROM transactions t                                                                                                                                                                                                                                                                                                                                                                                          +
                   WHERE split_part(t.id, '-'::text, 2) = cei.customer_id AND t.keterangan = 'pemasukan'::text AND t.status = 'Verified'::text AND EXTRACT(month FROM (t."timestamp" AT TIME ZONE 'Asia/Jakarta'::text)) = EXTRACT(month FROM cei.virtual_due_date) AND EXTRACT(year FROM (t."timestamp" AT TIME ZONE 'Asia/Jakarta'::text)) = EXTRACT(year FROM cei.virtual_due_date))) AND cei.virtual_due_date <= CURRENT_DATE+
         )                                                                                                                                                                                                                                                                                                                                                                                                                       +
  SELECT node AS "NODE",                                                                                                                                                                                                                                                                                                                                                                                                         +
     sum(                                                                                                                                                                                                                                                                                                                                                                                                                        +
         CASE                                                                                                                                                                                                                                                                                                                                                                                                                    +
             WHEN (CURRENT_DATE - virtual_due_date) <= 30 THEN expected_amount                                                                                                                                                                                                                                                                                                                                                   +
             ELSE 0::numeric                                                                                                                                                                                                                                                                                                                                                                                                     +
         END) AS "REAL 0-30 DAYS",                                                                                                                                                                                                                                                                                                                                                                                               +
     sum(                                                                                                                                                                                                                                                                                                                                                                                                                        +
         CASE                                                                                                                                                                                                                                                                                                                                                                                                                    +
             WHEN (CURRENT_DATE - virtual_due_date) >= 31 AND (CURRENT_DATE - virtual_due_date) <= 60 THEN expected_amount                                                                                                                                                                                                                                                                                                       +
             ELSE 0::numeric                                                                                                                                                                                                                                                                                                                                                                                                     +
         END) AS "REAL 31-60 DAYS",                                                                                                                                                                                                                                                                                                                                                                                              +
     sum(                                                                                                                                                                                                                                                                                                                                                                                                                        +
         CASE                                                                                                                                                                                                                                                                                                                                                                                                                    +
             WHEN (CURRENT_DATE - virtual_due_date) >= 61 AND (CURRENT_DATE - virtual_due_date) <= 90 THEN expected_amount                                                                                                                                                                                                                                                                                                       +
             ELSE 0::numeric                                                                                                                                                                                                                                                                                                                                                                                                     +
         END) AS "REAL 61-90 DAYS",                                                                                                                                                                                                                                                                                                                                                                                              +
     sum(                                                                                                                                                                                                                                                                                                                                                                                                                        +
         CASE                                                                                                                                                                                                                                                                                                                                                                                                                    +
             WHEN (CURRENT_DATE - virtual_due_date) > 90 THEN expected_amount                                                                                                                                                                                                                                                                                                                                                    +
             ELSE 0::numeric                                                                                                                                                                                                                                                                                                                                                                                                     +
         END) AS "REAL 90+ DAYS"                                                                                                                                                                                                                                                                                                                                                                                                 +
    FROM unpaidinvoices                                                                                                                                                                                                                                                                                                                                                                                                          +
   GROUP BY node                                                                                                                                                                                                                                                                                                                                                                                                                 +
   ORDER BY (sum(                                                                                                                                                                                                                                                                                                                                                                                                                +
         CASE                                                                                                                                                                                                                                                                                                                                                                                                                    +
             WHEN (CURRENT_DATE - virtual_due_date) > 90 THEN expected_amount                                                                                                                                                                                                                                                                                                                                                    +
             ELSE 0::numeric                                                                                                                                                                                                                                                                                                                                                                                                     +
         END)) DESC;
(1 row)

